/// Mirrors the backend's `NotificationType` — only the two event types the
/// backend ever sends to a CLIENT recipient. `unknown` is a forward-compat
/// fallback so an unrecognized future type never crashes parsing.
enum TravelNotificationType { itineraryPublished, itineraryChanged, unknown }

/// A notification generated by the backend (`GET /notifications`) about a
/// change in one of the client's travels — read/unread state and event
/// generation both live on the server, not on this device.
class TravelNotification {
  final String id;
  final String travelId;
  final TravelNotificationType type;
  final DateTime createdAt;
  final bool read;

  const TravelNotification({
    required this.id,
    required this.travelId,
    required this.type,
    required this.createdAt,
    this.read = false,
  });

  TravelNotification copyWith({bool? read}) => TravelNotification(
        id: id,
        travelId: travelId,
        type: type,
        createdAt: createdAt,
        read: read ?? this.read,
      );
}
