import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:intl/intl.dart';
import 'package:provider/provider.dart';
import 'package:travel_matrix/app/global_controllers/notifications_badge_controller.dart';
import 'package:travel_matrix/app/router/app_routes.dart';
import 'package:travel_matrix/features/notifications/domain/entities/travel_notification.dart';
import 'package:travel_matrix/features/notifications/presentation/controllers/notifications_controller.dart';
import 'package:travel_matrix/l10n/app_localizations.dart';

/// Notification list backed by `GET /notifications` — every entry here was
/// generated by the backend at the moment a client created/edited a route,
/// not derived on-device.
class NotificationsPage extends StatelessWidget {
  const NotificationsPage({super.key, this.controller});

  /// Injectable for widget tests with a fixed state, without depending on
  /// the real network/singleton wiring. In production the call site is
  /// unaffected — the default wiring is used.
  final NotificationsController? controller;

  @override
  Widget build(BuildContext context) {
    return ChangeNotifierProvider(
      // Marking a notification read never touches the sidebar's badge on
      // its own (separate provider scope) — this is the one place both are
      // reachable, so the controller reports back to it directly instead of
      // relying on whichever exit widget happens to be on screen.
      create: (context) =>
          controller ?? NotificationsController(onReadStateChanged: context.read<NotificationsBadgeController>().refresh),
      child: const _NotificationsView(),
    );
  }
}

class _NotificationsView extends StatelessWidget {
  const _NotificationsView();

  @override
  Widget build(BuildContext context) {
    final l10n = AppLocalizations.of(context)!;
    final controller = context.watch<NotificationsController>();
    final state = controller.state;
    final hasUnread = state.notifications.any((n) => !n.read);

    return Scaffold(
      appBar: AppBar(
        // No custom `leading` — the default back button already hides
        // itself when there's nothing to pop (e.g. a direct link straight
        // to this route), instead of asserting.
        title: Text(l10n.notificationsTitle),
        actions: [
          TextButton(
            onPressed: hasUnread ? controller.markAllRead : null,
            child: Text(l10n.notificationsMarkAllRead),
          ),
        ],
      ),
      body: state.isLoading
          ? const Center(child: CircularProgressIndicator())
          : state.isError
              ? _NotificationsStatusView(
                  icon: Icons.error_outline,
                  iconColor: Theme.of(context).colorScheme.error,
                  message: l10n.failedToLoadNotifications,
                  action: OutlinedButton(onPressed: controller.retry, child: Text(l10n.retryButton)),
                )
              : state.notifications.isEmpty
                  ? _NotificationsStatusView(
                      icon: Icons.notifications_off_outlined,
                      title: l10n.notificationsEmptyTitle,
                      message: l10n.notificationsEmptyMessage,
                    )
                  : _NotificationsListView(state: state),
    );
  }
}

/// Centered icon + optional title + message + optional action — the empty
/// and error states differ only in those four things.
class _NotificationsStatusView extends StatelessWidget {
  const _NotificationsStatusView({required this.icon, this.iconColor, this.title, required this.message, this.action});

  final IconData icon;
  final Color? iconColor;
  final String? title;
  final String message;
  final Widget? action;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);

    return Center(
      child: Padding(
        padding: const EdgeInsets.all(24),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Icon(icon, size: 40, color: iconColor ?? theme.colorScheme.onSurface.withValues(alpha: 0.4)),
            const SizedBox(height: 12),
            if (title != null) ...[
              Text(title!, style: theme.textTheme.titleMedium?.copyWith(fontWeight: FontWeight.w600)),
              const SizedBox(height: 4),
            ],
            Text(
              message,
              textAlign: TextAlign.center,
              style: theme.textTheme.bodySmall?.copyWith(color: theme.colorScheme.onSurface.withValues(alpha: 0.6)),
            ),
            if (action != null) ...[const SizedBox(height: 12), action!],
          ],
        ),
      ),
    );
  }
}

class _NotificationsListView extends StatelessWidget {
  const _NotificationsListView({required this.state});

  final NotificationsState state;

  @override
  Widget build(BuildContext context) {
    // Flattened once per build (cheap — no widgets built yet) so
    // ListView.builder can lazily build only what's on screen, instead of
    // materializing every loaded page's tiles up front.
    final rows = <Object>[
      for (final group in groupNotificationsByDay(state.notifications)) ...[group, ...group.notifications],
    ];

    return NotificationListener<ScrollNotification>(
      onNotification: (notification) {
        final metrics = notification.metrics;
        if (metrics.pixels >= metrics.maxScrollExtent - 200) {
          context.read<NotificationsController>().loadMore();
        }
        return false;
      },
      child: ListView.builder(
        padding: const EdgeInsets.all(16),
        itemCount: rows.length + (state.isLoadingMore ? 1 : 0),
        itemBuilder: (context, index) {
          if (index >= rows.length) {
            return const Padding(
              padding: EdgeInsets.symmetric(vertical: 16),
              child: Center(child: CircularProgressIndicator()),
            );
          }

          final row = rows[index];
          if (row is NotificationDayGroup) {
            return Padding(
              padding: const EdgeInsets.fromLTRB(4, 12, 4, 8),
              child: Text(
                row.label(context).toUpperCase(),
                style: Theme.of(context).textTheme.labelMedium?.copyWith(
                      color: Theme.of(context).colorScheme.onSurface.withValues(alpha: 0.6),
                      letterSpacing: 0.4,
                    ),
              ),
            );
          }
          return _NotificationTile(notification: row as TravelNotification);
        },
      ),
    );
  }
}

class _NotificationTile extends StatelessWidget {
  const _NotificationTile({required this.notification});

  final TravelNotification notification;

  @override
  Widget build(BuildContext context) {
    final l10n = AppLocalizations.of(context)!;
    final theme = Theme.of(context);
    final isUnread = !notification.read;

    return InkWell(
      borderRadius: BorderRadius.circular(10),
      onTap: () => _open(context),
      child: Container(
        margin: const EdgeInsets.only(bottom: 8),
        padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 14),
        decoration: BoxDecoration(
          color: isUnread ? theme.colorScheme.primary.withValues(alpha: 0.03) : theme.colorScheme.surface,
          borderRadius: BorderRadius.circular(10),
          border: Border.all(color: theme.colorScheme.outlineVariant),
        ),
        child: Row(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Icon(_iconFor(notification.type), size: 18, color: theme.colorScheme.primary),
            const SizedBox(width: 12),
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    _messageFor(notification.type, l10n),
                    style: theme.textTheme.bodyMedium?.copyWith(
                      fontWeight: isUnread ? FontWeight.w600 : FontWeight.w400,
                    ),
                  ),
                  const SizedBox(height: 4),
                  Text(
                    _formatTime(context, notification.createdAt),
                    style: theme.textTheme.bodySmall?.copyWith(color: theme.colorScheme.onSurface.withValues(alpha: 0.5)),
                  ),
                ],
              ),
            ),
            if (isUnread)
              Container(
                margin: const EdgeInsets.only(left: 8, top: 2),
                width: 8,
                height: 8,
                decoration: BoxDecoration(color: theme.colorScheme.primary, shape: BoxShape.circle),
              ),
          ],
        ),
      ),
    );
  }

  void _open(BuildContext context) {
    context.read<NotificationsController>().markAsRead(notification.id);
    // `push` would stack this route on top of whatever branch happens to be
    // current, even though `/travels/{id}` belongs to the Booking branch —
    // `go` re-resolves the location against the shell's branches, switching
    // to Booking and landing there directly.
    context.go('${AppRoutes.travels}/${notification.travelId}');
  }

  String _formatTime(BuildContext context, DateTime dateTime) {
    return DateFormat.Hm(AppLocalizations.of(context)!.localeName).format(dateTime);
  }

  IconData _iconFor(TravelNotificationType type) => switch (type) {
        TravelNotificationType.routeCreated => Icons.route_outlined,
        TravelNotificationType.routeEdited => Icons.edit_road_outlined,
        TravelNotificationType.unknown => Icons.notifications_outlined,
      };

  String _messageFor(TravelNotificationType type, AppLocalizations l10n) => switch (type) {
        TravelNotificationType.routeCreated => l10n.notificationRouteCreated,
        TravelNotificationType.routeEdited || TravelNotificationType.unknown => l10n.notificationRouteEdited,
      };
}

/// One day's worth of notifications, in the order they should render.
class NotificationDayGroup {
  const NotificationDayGroup({required this.day, required this.notifications});

  final DateTime day;
  final List<TravelNotification> notifications;

  /// "Today"/"Yesterday" for the two closest days, "d MMM" otherwise.
  String label(BuildContext context) {
    final l10n = AppLocalizations.of(context)!;
    final now = DateTime.now();
    final today = DateTime(now.year, now.month, now.day);
    final yesterday = today.subtract(const Duration(days: 1));

    if (day == today) return l10n.notificationsToday;
    if (day == yesterday) return l10n.notificationsYesterday;

    return DateFormat('d MMM', l10n.localeName).format(day);
  }
}

/// Buckets [notifications] (assumed already sorted newest-first) into
/// consecutive same-day groups, preserving that order.
List<NotificationDayGroup> groupNotificationsByDay(List<TravelNotification> notifications) {
  final groups = <NotificationDayGroup>[];

  for (final notification in notifications) {
    final day = DateTime(notification.createdAt.year, notification.createdAt.month, notification.createdAt.day);
    if (groups.isNotEmpty && groups.last.day == day) {
      groups.last.notifications.add(notification);
    } else {
      groups.add(NotificationDayGroup(day: day, notifications: [notification]));
    }
  }

  return groups;
}
